### PR TITLE
Updated to latest Spark version

### PR DESCRIPTION
**Pull request by michaelkamprath**
Updated the Spark and Scala versions so that TeraSort can run with the latest Spark version. Also updated the `scala-maven-plugin`.  Adjusted the README notes as appropriate for the version changes.

### CODE REVIEW

**Comment by michaelkamprath** [comment]
@ehiggs Looks like the build test is failing because the build environment is missing `javax/tools/ToolProvider`. Not sure what is going on there. I will say this builds fine for me. I do it as part of a docker image build, and use the ` openjdk-8-jdk` version of Java. Looks like the build environment is using Java 11.0.2. Note that Spark does not work with Java 9 and beyond (at least Spark 2.x and below, 3.x is expected to) because it used the `sun.misc.Unsafe` classes. Maybe the build environment needs to regress the version of Java used?

**Comment by ehiggs** [comment]
[I just built master and it works still](https://travis-ci.org/ehiggs/spark-terasort/builds/635844138) so it's quite strange.

Spark 3 is almost released so I'm happy to wait on digging too deep into this now to support EOL jdk versions.

**Comment by michaelkamprath** [comment]
@ehiggs OK, I [did some research](https://github.com/dmlc/xgboost/issues/4000#issuecomment-448603560) and corrected the build. The issue was rooted in that Spark 2.4.4 uses a different Scala version than Spark 2.4.2 (the version the master branch is currently on). That difference in version was preventing the master branch from running on my Spark 2.4.4 cluster. But when I fixed the build for Spark 2.4.4, that broke the `scala-maven-plugin` with Scala 2.11 on the latest JVM which your build environment uses (works fine with Java 8, which is what Spark 2.x uses). Anyway, the fix was to update some arguments to `scala-maven-plugin`. It now builds in your build environment and with Java 8 (my cluster's environment).

**Comment by ehiggs** [comment]
Thanks for the PR @michaelkamprath and digging in deep to get the build working. Can I add you to the AUTHORS file?

Thanks again!

**Comment by michaelkamprath** [comment]
@ehiggs I wouldn't consider the configuration changes I made as "authorship", but if you want to add me I don't mind.

**Pull request merged**
